service: go-api

provider:
  name: aws
  region: us-east-1
  architecture: x86_64
  logs:
    httpApi: true
  httpApi:
    cors: true
  timeout: 10
  memorySize: 256

ecr:
  images:
    appimage:
      path: .

functions:
  app:
    image: appimage
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY
