name: Deploy Lambda

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [staging, production]

    if: github.ref == 'refs/heads/' + matrix.env

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build Go binary
        run: |
          mkdir -p build/${{ matrix.env }}
          GOOS=linux GOARCH=amd64 go build -o build/${{ matrix.env }}/bootstrap app/main.go
          cd build/${{ matrix.env }} && zip bootstrap.zip bootstrap

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy with Terraform
        run: |
          cd infra
          terraform init
          terraform apply -auto-approve -var-file="env/${{ matrix.env }}.tfvars"
